-- Web Push keeps durable inbox rows as the source of truth while delivering
-- a per-device copy through the browser push service.
CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;

CREATE TABLE public.push_subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  endpoint TEXT NOT NULL UNIQUE,
  p256dh TEXT NOT NULL,
  auth_key TEXT NOT NULL,
  expiration_time BIGINT,
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT push_subscriptions_endpoint_length
    CHECK (CHAR_LENGTH(endpoint) BETWEEN 16 AND 4096),
  CONSTRAINT push_subscriptions_p256dh_length
    CHECK (CHAR_LENGTH(p256dh) BETWEEN 16 AND 512),
  CONSTRAINT push_subscriptions_auth_key_length
    CHECK (CHAR_LENGTH(auth_key) BETWEEN 8 AND 256)
);

CREATE INDEX push_subscriptions_user_updated_idx
  ON public.push_subscriptions(user_id, updated_at DESC);

ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own push subscriptions"
  ON public.push_subscriptions
  FOR SELECT
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can create own push subscriptions"
  ON public.push_subscriptions
  FOR INSERT
  TO authenticated
  WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can update own push subscriptions"
  ON public.push_subscriptions
  FOR UPDATE
  TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can delete own push subscriptions"
  ON public.push_subscriptions
  FOR DELETE
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);

REVOKE ALL ON TABLE public.push_subscriptions FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.push_subscriptions TO authenticated;

CREATE TABLE public.notification_push_deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_id UUID NOT NULL REFERENCES public.notifications(id) ON DELETE CASCADE,
  subscription_id UUID REFERENCES public.push_subscriptions(id) ON DELETE SET NULL,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'processing', 'retry', 'delivered', 'expired', 'failed')),
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count BETWEEN 0 AND 20),
  available_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  claimed_at TIMESTAMPTZ,
  delivered_at TIMESTAMPTZ,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (notification_id, subscription_id)
);

CREATE INDEX notification_push_deliveries_claim_idx
  ON public.notification_push_deliveries(status, available_at, created_at)
  WHERE status IN ('pending', 'retry');

CREATE INDEX notification_push_deliveries_user_created_idx
  ON public.notification_push_deliveries(user_id, created_at DESC);

ALTER TABLE public.notification_push_deliveries ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.notification_push_deliveries FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.notification_push_deliveries TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.notification_push_deliveries_id_seq TO service_role;

CREATE OR REPLACE FUNCTION private.enqueue_notification_push_deliveries()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.notification_push_deliveries (
    notification_id,
    subscription_id,
    user_id
  )
  SELECT
    NEW.id,
    subscription.id,
    NEW.user_id
  FROM public.push_subscriptions subscription
  WHERE subscription.user_id = NEW.user_id
  ON CONFLICT (notification_id, subscription_id) DO NOTHING;

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION private.enqueue_notification_push_deliveries() IS
  'Creates one Web Push delivery per registered device when an inbox row is inserted.';

REVOKE ALL ON FUNCTION private.enqueue_notification_push_deliveries()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS notifications_enqueue_web_push ON public.notifications;
CREATE TRIGGER notifications_enqueue_web_push
  AFTER INSERT ON public.notifications
  FOR EACH ROW
  EXECUTE FUNCTION private.enqueue_notification_push_deliveries();

-- Vault entries are configured outside migration history:
-- habit_garden_project_url and habit_garden_secret_key.
CREATE OR REPLACE FUNCTION private.invoke_web_push_dispatcher()
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_project_url TEXT;
  v_secret_key TEXT;
  v_request_id BIGINT;
BEGIN
  SELECT secret.decrypted_secret
  INTO v_project_url
  FROM vault.decrypted_secrets secret
  WHERE secret.name = 'habit_garden_project_url'
  LIMIT 1;

  SELECT secret.decrypted_secret
  INTO v_secret_key
  FROM vault.decrypted_secrets secret
  WHERE secret.name = 'habit_garden_secret_key'
  LIMIT 1;

  IF NULLIF(BTRIM(v_project_url), '') IS NULL
    OR NULLIF(BTRIM(v_secret_key), '') IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT net.http_post(
    url := RTRIM(v_project_url, '/') || '/functions/v1/push-notifications',
    headers := JSONB_BUILD_OBJECT(
      'Content-Type', 'application/json',
      'apikey', v_secret_key,
      'Authorization', 'Bearer ' || v_secret_key
    ),
    body := JSONB_BUILD_OBJECT(
      'source', 'habit-web-push-dispatcher',
      'invoked_at', NOW()
    )
  )
  INTO v_request_id;

  RETURN v_request_id;
END;
$$;

COMMENT ON FUNCTION private.invoke_web_push_dispatcher() IS
  'Invokes the Web Push Edge Function when project URL and secret key exist in Vault.';

REVOKE ALL ON FUNCTION private.invoke_web_push_dispatcher()
  FROM PUBLIC, anon, authenticated;

DO $$
DECLARE
  v_job_id BIGINT;
BEGIN
  FOR v_job_id IN
    SELECT jobid FROM cron.job WHERE jobname = 'habit-web-push-dispatcher'
  LOOP
    PERFORM cron.unschedule(v_job_id);
  END LOOP;
END;
$$;

SELECT cron.schedule(
  'habit-web-push-dispatcher',
  '* * * * *',
  $cron$SELECT private.invoke_web_push_dispatcher()$cron$
);
